#!/bin/bash

### X server configuration
xset s off
xset -dpms
xsetroot -cursor_name left_ptr
### end

### desktop area configurations
picom --backend xrender -b
nvidia-settings --load-config-only
feh --bg-fill $HOME/.wallpaper.jpg
sxhkd &
dunst &
lxpolkit &
~/.config/polybar/launch.sh --forest
### end


### BSPWM internals configurations
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

### end
